### ISSUE TITLE
Follow Bot

### ISSUE THREAD

**Issue by Nxshy** [useragents/Proxyless-Spotify-Follow-Bot#1]
what do i do for thread and when i do it spams Error and i do 10 thread any help but one min ago it started following but then stopped?

**Comment by Nxshy** [comment]
and how do i put my link in?

**Comment by useragents** [comment]
`Error` likely means that you're rate-limited by Spotify as they only allow you to create 200 accounts per IP. 

You can put your Spotify link in by opening `main.py` in a text editor or other, then changing the variable `spotify_profile`'s value to your Spotify link.

![image](https://user-images.githubusercontent.com/103281345/162620501-cbb5fbdb-eb7c-4179-8806-6be87ca858c9.png)
