### ISSUE TITLE
doesnt even send the follows now. it goes forever and ever but never actually sends them when i refresh and look

### ISSUE THREAD

**Issue by Nxshy** [useragents/Proxyless-Spotify-Follow-Bot#10]
![image](https://user-images.githubusercontent.com/103340977/162964734-0ee5fff1-34a9-435e-a2e3-5109cffe45c6.png)

**Comment by useragents** [comment]
Looking into it. 👍

**Comment by Tommy512JJ** [comment]
same

**Comment by v6r** [comment]
bump @useragents

**Comment by veast-network** [comment]
Have you changed the URL in main.py?

**Comment by v6r** [comment]
> Have you changed the URL in main.py?

yes does it work for you atm?

**Comment by Zeunig** [comment]
You're rate limited, Spotify's not gonna let you to create accounts for a while.

**Comment by v6r** [comment]
> 

it never worked for me lol

**Comment by useragents** [comment]
Fixed this issue, also added proxy support 👍
