### ISSUE TITLE
No followers

### ISSUE THREAD

**Issue by 009IE** [useragents/Proxyless-Spotify-Follow-Bot#11]
Just says Follower ' 1 ' and so on but no followers 🤣
![image](https://user-images.githubusercontent.com/103905194/163733774-ff195b18-eef6-4e41-9943-a5429d7c8108.png)

**Comment by veast-network** [comment]
try changing the url in main.py. Hope this helps!

**Comment by lvzare** [comment]
> try changing the url in main.py. Hope this helps!

i only get 200 followers per a 20 minute

**Comment by veast-network** [comment]
> > try changing the url in main.py. Hope this helps!
> 
> i only get 200 followers per a 20 minute

The program is proxyless. Spotify usually limits the accounts you can register by IP to 150-200 before you get ratelimited.

**Comment by lvzare** [comment]
> > > try changing the url in main.py. Hope this helps!
> > 
> > 
> > i only get 200 followers per a 20 minute
> 
> The program is proxyless. Spotify usually limits the accounts you can register by IP to 150-200 before you get ratelimited.

how do iadd proxys

**Comment by veast-network** [comment]
You can't add proxies on this program. The creator hasn't implemented it.

**Comment by useragents** [comment]
@lvzare There is no proxy support as of the time of this comment, it will be added in the next update.

@009IE I am aware of the current issue and I am working on it.
