### ISSUE TITLE
question

### ISSUE THREAD

**Issue by euiruhieer** [useragents/Proxyless-Spotify-Follow-Bot#12]
Can you make a follow bot with no limit?

**Comment by veast-network** [comment]
There *technically* is no limit. You are kind of limited by Spotify limiting the accounts you can make by IP (150-200). If the creator made a version that uses proxies, you would have far less limits.

However, the program does **not** let you use proxies. Therefore you are limited to 150-200 followers per IP. You can resolve this by either waiting or using a VPN.

**Comment by useragents** [comment]
I can add proxy support in the next update. 👍
