### ISSUE TITLE
"Client credentials authentication not allowed"

### ISSUE THREAD

**Issue by yuriwithdaggers** [useragents/Proxyless-Spotify-Follow-Bot#13]
I have already redone the entire code in search of a solution to this problem but it is simply impossible to solve it.

In the last function, "follow", the session.put returns me this json:

`{\n  "error" : {\n    "status" : 400,\n    "message" : "Client credentials authentication not allowed"\n  }\n}
`

**Comment by useragents** [comment]
What part did you redo?

**Comment by useragents** [comment]
It is pointless to redo another apart from the follow function as the others work fine. I am looking into it now 👍

**Comment by yuriwithdaggers** [comment]
The original code was returning me this error.

I tried to fix it anyway, it kept coming back to me.

**Comment by useragents** [comment]
Yes, the original code returns that response.

**Comment by yuriwithdaggers** [comment]
Since you didn't want to help:

The error was in the concatenation of the login_token with the URL

If anyone has the same problem.
