### ISSUE TITLE
Spotify follower limit / non-proxy related issue (?)

### ISSUE THREAD

**Issue by Exaed** [useragents/Proxyless-Spotify-Follow-Bot#15]
After using it for a while my Spotify followers maxed out at exactly 1,000... is this because the bot is proxy less or is it a Spotify follower limit?

**Comment by Anydex** [comment]
yeah same, I added proxy support and it capped out at 1k.

**Comment by useragents** [comment]
Fixed this issue, also added proxy support 👍
