### ISSUE TITLE
main.py immediately closes.

### ISSUE THREAD

**Issue by calebidklol** [useragents/Proxyless-Spotify-Follow-Bot#17]
I run it, then it immediately closes.

**Comment by useragents** [comment]
Type `pip install requests` in Command Prompt and let me know if this fixed your issue.

**Comment by calebidklol** [comment]
> 

Nope, does the same thing.

**Comment by useragents** [comment]
That's strange. Let's use the Command Prompt to run the Python script to catch the error before it immediately closes. Watch this YouTube video [here](https://www.youtube.com/watch?v=pFYcAOsNyvs) and proceed with the steps shown. Show me what is outputted by the Python script.

**Comment by calebidklol** [comment]
Oh, I got it to work, I didn't change anything, but now I am getting rate limited even though I haven't made any accounts today. I would use proxies but all of them say bad proxy.

**Comment by useragents** [comment]
This script works perfectly as of now, so this is an issue from your end. If you're using the proxy-less option, be aware that Spotify blacklists some VPN IPs.
