### ISSUE TITLE
can't find proxy.txt

### ISSUE THREAD

**Issue by richwarrior1** [useragents/Proxyless-Spotify-Follow-Bot#22]
![image](https://user-images.githubusercontent.com/103997462/166102719-ae5f26b1-87d9-4d04-9cb0-d38f32fcc9de.png)

how can i solve

**Comment by useragents** [comment]
Make a file and name it `proxies.txt` and put your proxy list inside of it (IP:port format)

**Comment by richwarrior1** [comment]
![image](https://user-images.githubusercontent.com/103997462/166141718-7ea5cf53-647f-403a-8682-c8f4b3b1e9e4.png)

there is such a file
