### ISSUE TITLE
constant ratelimit

### ISSUE THREAD

**Issue by Lackins** [useragents/Proxyless-Spotify-Follow-Bot#23]
When running main.py it just spams "ratelimit" 
![image](https://user-images.githubusercontent.com/101938176/166120369-f4f3dd14-11ff-4f49-8eb8-26e770737cc8.png)

**Comment by Tygex** [comment]
i got the same problem it wanted 1k but it stopped at 400 what do i do next ?

**Comment by useragents** [comment]
This is not an issue with my script. Spotify ratelimits you after a specific amount of accounts have been registered. Change your IP or use proxies. @Tygex @Lackins
