### ISSUE TITLE
Big issue

### ISSUE THREAD

**Issue by MAGames77** [useragents/Proxyless-Spotify-Follow-Bot#25]
yo the follow bot is not working properly after 200 follows it spams "error will registering rate limit" if u can pls fix it and if there is a problem with the accounts make it as people have to enter the accounts themselves /pls add a way to make a discord bot out of it

**Comment by useragents** [comment]
The follow bot is working perfectly fine with no issues. This "issue" is because of Spotify's rate limit which is why it tells you there's an error while registering. To prevent this, you can use proxies that you can find online or buy them from somewhere.
