### ISSUE TITLE
not sending follows after 24 hours using proxies

### ISSUE THREAD

**Issue by x198x** [useragents/Proxyless-Spotify-Follow-Bot#30]
I used it 2 days ago and used proxies and i got 15k follows , i used it today with different proxies and its not working

**Comment by useragents** [comment]
Please check your follower list rather than follower count as it may the follow count take a while to update.

**Comment by Dinastania** [comment]
can i have the proxies list pls bro?

**Comment by useragents** [comment]
I don’t provide proxies.
