### ISSUE TITLE
Error while importing modules. Please install the modules in requirements.txt

### ISSUE THREAD

**Issue by vlusko** [useragents/Proxyless-Spotify-Follow-Bot#36]
it says Error while importing modules. Please install the modules in requirements.txt how do i fix and then when i got to requirements and follow the rules when i do the thing in cmd it says this 'pip' is not recognized as an internal or external command,
operable program or batch file. also can u send me ur discord sever link how do i fix help plz

**Comment by useragents** [comment]
This is unrelated to an issue with my script, please view https://pip.pypa.io/en/stable/installation/ to learn how to install PIP. Please ensure you only have 1 Python installed as the modules may install to the wrong path.
