### ISSUE TITLE
how to make run properly ?

### ISSUE THREAD

**Issue by toxickush** [useragents/Proxyless-Spotify-Follow-Bot#37]
i installed the requirements .txt fine but im not too sure as to what else the code needs changed to run properly ? 

i run it and all my idle shell shows is this

 = RESTART: C:\Users\oacoo\OneDrive\Desktop\bots\bot\xoldver\likesmodule\followbot\Proxyless-Spotify-Follow-Bot-main\main.py
xxxxxdemolinkxxxxx

my code is as follows.. i have no proxies to use just a VPN.

from follow_bot import spotify
import threading, os, time

lock = threading.Lock()
counter = 0
proxies = []
proxy_counter = 0
spotify_profile = str(input("xxxxxdemolinkxxxxx"))
threads = int(input("\nThreads: "))

def load_proxies():
    if not os.path.exists("proxies.txt"):
        print("\nFile proxies.txt not found")
        time.sleep(10)
        os._exit(0)
    with open("proxies.txt", "r", encoding = "UTF-8") as f:
        for line in f.readlines():
            line = line.replace("\n", "")
            proxies.append(line)
        if not len(proxies):
            print("\nNo proxies loaded in proxies.txt")
            time.sleep(10)
            os._exit(0)

print("\n[1] Proxies\n[2] Proxyless")
option = int(input("\n> "))
if option == 1:
    load_proxies()

def safe_print(arg):
    lock.acquire()
    print(arg)
    lock.release()

def thread_starter():
    global counter
    if option == 1:
        obj = spotify(spotify_profile, proxies[proxy_counter])
    else:
        obj = spotify(spotify_profile)
    result, error = obj.follow()
    if result == True:
        counter += 1
        safe_print("Followed {}".format(counter))
    else:
        safe_print(f"Error {error}")

while True:
    if threading.active_count() <= threads:
        try:
            threading.Thread(target = thread_starter).start()
            proxy_counter += 1
        except:
            pass
        if len(proxies) <= proxy_counter: #Loops through proxy file
            proxy_counter = 0

**Comment by useragents** [comment]
Spotify has blacklisted several VPN IP addresses from register, depending on what VPN you have. For example, my current VPN Mullvad works fine but I tested HMA and they blacklisted their IP addresses. You do not have to edit any of the files whatsoever, just run it and enter your Spotify link/username.
