### ISSUE TITLE
Proxyless (Mode 2) Error

### ISSUE THREAD

**Issue by FlipfudgeV2** [useragents/Proxyless-Spotify-Follow-Bot#40]
Error bad proxy on register None
Error bad proxy on register None
Error bad proxy on register None
Error bad proxy on register None
Error bad proxy on register None
Error bad proxy on register None
Error bad proxy on register None
Error bad proxy on register None

That's the error. To be clear, I chose option 2, so I shouldn't have needed proxies.
Thanks!

**Comment by useragents** [comment]
This is a mistake with output, although it is not trying to use proxies. I have handled this error properly and now it will return `unable to send request on register` if the request is not going through. Ignoring what was outputted to you (fixed), this means that when the script was trying to create accounts, the requests were not being sent for whatever reason (likely bad connection/no internet).

🟢 This script is still working as of 6/6/22.
