### ISSUE TITLE
all account locked/incorrect password

### ISSUE THREAD

**Issue by Minhe173** [useragents/Proxyless-Spotify-Follow-Bot#44]

**Comment by Minhe173** [comment]
@useragents

**Comment by 8zj** [comment]
Ok So Yeah There Botting lol they gonna be locked after like 1 week but you should use a account gen if you want accounts lol

**Comment by Minhe173** [comment]
send me acc gen

**Comment by useragents** [comment]
This is a follow bot, not an account creator. My script does create Spotify accounts, sometimes Spotify bans all accounts with the same registered IP.

**Comment by Minhe173** [comment]
Can u add proxy option? @useragents i want to use this tool with proxy

**Comment by Minhe173** [comment]
@useragents
