### ISSUE TITLE
Error while registering, ratelimit

### ISSUE THREAD

**Issue by kinoshisocial** [useragents/Proxyless-Spotify-Follow-Bot#45]
![unknown](https://user-images.githubusercontent.com/73155590/174874182-01919bb0-6a14-4a74-aa93-3d4511c4a00b.png)

**Comment by Oxy-py** [comment]
same

**Comment by useragents** [comment]
Please google what a rate limit is before creating an issue. The script has proxy support in the latest version.
@kinoshisocial @Oxy-py
