### ISSUE TITLE
"Error" 

### ISSUE THREAD

**Issue by lkeld** [useragents/Proxyless-Spotify-Follow-Bot#5]
I'll get like 100 followers then it will stop working, idk if its a ratelimit but i tried using a vpn to change my ip and its still giving me the same error code. 
![image](https://user-images.githubusercontent.com/48638597/162624166-017be731-c848-4925-94c1-835237ec959e.png)

**Comment by useragents** [comment]
`Error` likely means that you're rate-limited by Spotify as they only allow you to create 200 accounts per IP.

Spotify blacklists most VPN IP addresses which also may result in `Error`

**Comment by lkeld** [comment]
are you able to add an option to use proxies, I have a bunch of residential proxies that are probably not blocked.

**Comment by useragents** [comment]
Yeah sure, I'll add proxy support soon. :)
