### ISSUE TITLE
Followers

### ISSUE THREAD

**Issue by cb-37** [useragents/Proxyless-Spotify-Follow-Bot#52]
I have received followers from this script without me using the script, they are named github.com/useragents is there a way to remove them as I was not the one to request the followers?

**Comment by Not-Mystify** [comment]
Unfortunately, there's currently no official way to mass remove followers. I'm sure you could write a script to do it.

**Comment by keyiflerolsun** [comment]
> I have received followers from this script without me using the script, they are named github.com/useragents is there a way to remove them as I was not the one to request the followers?

You can use my repo and this line change `tr` to `en`

https://github.com/keyiflerolsun/SpotifyTakipci/blob/main/main.py#L15

**Comment by ArdaKurucim** [comment]
This script saves the generated users into a TXT file just make the script serialize the file and make it to login these users instead of creating new ones and use the unfollow api.

**Comment by kanjvt** [comment]
> > I have received followers from this script without me using the script, they are named github.com/useragents is there a way to remove them as I was not the one to request the followers?
> 
> You can use my repo and this line change `tr` to `en`
> 
> https://github.com/keyiflerolsun/SpotifyTakipci/blob/main/main.py#L15

error bro https://telegra.ph/file/b95bcf9ca72254322fad9.jpg

**Comment by keyiflerolsun** [comment]
> > > I have received followers from this script without me using the script, they are named github.com/useragents is there a way to remove them as I was not the one to request the followers?
> > 
> > 
> > You can use my repo and this line change `tr` to `en`
> > https://github.com/keyiflerolsun/SpotifyTakipci/blob/main/main.py#L15
> 
> error bro https://telegra.ph/file/b95bcf9ca72254322fad9.jpg

you should use python 3.10.x bro :)
